after_success:
- mvn test javadoc:javadoc
before_install:
- wget dist.neo4j.org/neo4j-community-2.2.3-unix.tar.gz
- tar -xzf neo4j-community-2.2.3-unix.tar.gz
- sed -i.bak s/dbms.security.auth_enabled=true/dbms.security.auth_enabled=false/g
  neo4j-community-2.2.3/conf/neo4j-server.properties
- neo4j-community-2.2.3/bin/neo4j start
jdk:
- oraclejdk8
language: java
script:
- touch NOW
- echo GIBSTUDYSTART $(date)
- mvn test -B
- echo GIBSTUDYEND $(date)
- cd $TRAVIS_BUILD_DIR
- if [ "$TRAVIS_OS_NAME" == "osx" ];        then echo TESTNUM $(find . -name TEST-*.xml
  -newer NOW | wc -l);        else echo TESTNUM $(find -name TEST-*.xml -newer NOW
  | wc -l);        fi
services:
- couchdb
- mongodb
sudo: false
